# Generated by Django 5.2.4 on 2025-09-15 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias_clinicas', '0002_rename_trtamientos_tratamientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuota', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ent', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_limite', models.DateField()),
                ('fecha_pago', models.DateTimeField()),
                ('pagado', models.BooleanField(default=False)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.cuotas')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.entregas')),
                ('hist_clin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.historiasclinicas')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
