# Generated by Django 5.2.4 on 2025-11-11 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0005_seguimientohc_odontologo'),
        ('pagos', '0001_initial'),
        ('personal', '0006_personal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='fecha_limite',
        ),
        migrations.AddField(
            model_name='pagos',
            name='registrado_por',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.cuotas'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagos.entregas'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='hist_clin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.historiasclinicas'),
        ),
    ]
