# Generated by Django 5.2.4 on 2025-11-11 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0005_seguimientohc_odontologo'),
        ('pagos', '0002_remove_pagos_fecha_limite_pagos_registrado_por_and_more'),
        ('personal', '0006_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='hist_clin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.historiasclinicas'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to='personal.personal'),
        ),
    ]
