# Generated by Django 5.2.4 on 2025-11-11 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0005_seguimientohc_odontologo'),
        ('pagos', '0003_alter_pagos_hist_clin_alter_pagos_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='hist_clin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.historiasclinicas'),
        ),
    ]
