# Generated by Django 5.2.4 on 2025-11-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_pagos_hist_clin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregas',
            new_name='TiposPagos',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='cuota',
        ),
        migrations.AlterModelOptions(
            name='tipospagos',
            options={'verbose_name': 'Tipo de pagos', 'verbose_name_plural': 'Tipos de pagos'},
        ),
        migrations.RenameField(
            model_name='pagos',
            old_name='entrega',
            new_name='tipo_pago',
        ),
        migrations.RenameField(
            model_name='tipospagos',
            old_name='nombre_ent',
            new_name='nombre_tipo_pago',
        ),
        migrations.DeleteModel(
            name='Cuotas',
        ),
    ]
