# Generated by Django 5.2.4 on 2025-11-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0006_alter_seguimientohc_fecha'),
        ('pagos', '0007_rename_entregas_tipospagos_remove_pagos_cuota_and_more'),
        ('personal', '0006_personal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('REGISTRO', 'Pago Registrado'), ('CANCELACION', 'Pago Cancelado')], max_length=20)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('tipo_pago_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('hist_clin_numero', models.IntegerField(blank=True, null=True)),
                ('paciente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hist_clin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_pagos', to='historias_clinicas.historiasclinicas')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_registros', to='pagos.pagos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria_pagos', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Auditoría de Pago',
                'verbose_name_plural': 'Auditorías de Pagos',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['fecha_accion'], name='pagos_audit_fecha_a_7f89e4_idx'), models.Index(fields=['pago'], name='pagos_audit_pago_id_5972cd_idx'), models.Index(fields=['hist_clin_id'], name='pagos_audit_hist_cl_424db3_idx')],
            },
        ),
    ]
