# Generated by Django 5.2.4 on 2025-11-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0006_alter_seguimientohc_fecha'),
        ('pagos', '0008_auditoriapagos'),
        ('personal', '0006_personal_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditoriapagos',
            name='pagos_audit_hist_cl_424db3_idx',
        ),
        migrations.RemoveField(
            model_name='auditoriapagos',
            name='ip_address',
        ),
        migrations.AddIndex(
            model_name='auditoriapagos',
            index=models.Index(fields=['hist_clin_numero'], name='pagos_audit_hist_cl_e7f368_idx'),
        ),
    ]
