# Generated by Django 5.2.4 on 2025-09-14 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0006_pacientes_genero'),
        ('personal', '0004_alter_personal_especialidades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarasDentales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cara', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cara Dental',
                'verbose_name_plural': 'Caras Dentales',
            },
        ),
        migrations.CreateModel(
            name='PiezasDentales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pd', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Pieza Dental',
                'verbose_name_plural': 'Piezas Dentales',
            },
        ),
        migrations.CreateModel(
            name='Trtamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.CreateModel(
            name='HistoriasClinicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_hc', models.TextField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.pacientes')),
            ],
            options={
                'verbose_name': 'Historia clinica',
                'verbose_name_plural': 'Historias clinicas',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hist_clin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.historiasclinicas')),
            ],
            options={
                'verbose_name': 'Seguimiento de historia clinica',
                'verbose_name_plural': 'Seguimiento de historia clinica',
            },
        ),
        migrations.CreateModel(
            name='DetallesHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cara_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.carasdentales')),
                ('hist_clin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.historiasclinicas')),
                ('pieza_dental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.piezasdentales')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historias_clinicas.trtamientos')),
            ],
            options={
                'verbose_name': 'Detalle de historio clinica',
                'verbose_name_plural': 'Detalles de historia clinica',
            },
        ),
    ]
