# Generated by Django 5.2.4 on 2025-09-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trtamientos',
            new_name='Tratamientos',
        ),
    ]
