# Generated by Django 5.2.4 on 2025-11-03 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0002_rename_trtamientos_tratamientos'),
        ('pacientes', '0011_merge_20251020_2214'),
        ('personal', '0006_personal_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleshc',
            options={'verbose_name': 'Detalle de historia clinica', 'verbose_name_plural': 'Detalles de historia clinica'},
        ),
        migrations.AlterModelOptions(
            name='seguimientohc',
            options={'verbose_name': 'Seguimiento de historia clinica', 'verbose_name_plural': 'Seguimientos de historia clinica'},
        ),
        migrations.RemoveField(
            model_name='detalleshc',
            name='hist_clin',
        ),
        migrations.RemoveField(
            model_name='historiasclinicas',
            name='desc_hc',
        ),
        migrations.RemoveField(
            model_name='seguimientohc',
            name='hist_clin',
        ),
        migrations.AddField(
            model_name='detalleshc',
            name='historia_clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='historias_clinicas.historiasclinicas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiasclinicas',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Motivo de Consulta/Descripción Inicial'),
        ),
        migrations.AddField(
            model_name='seguimientohc',
            name='historia_clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='historias_clinicas.historiasclinicas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleshc',
            name='cara_dental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_hc', to='historias_clinicas.carasdentales'),
        ),
        migrations.AlterField(
            model_name='detalleshc',
            name='pieza_dental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_hc', to='historias_clinicas.piezasdentales'),
        ),
        migrations.AlterField(
            model_name='detalleshc',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_hc', to='historias_clinicas.tratamientos'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_atendidas', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='historiasclinicas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas', to='pacientes.pacientes'),
        ),
        migrations.AlterField(
            model_name='piezasdentales',
            name='codigo_pd',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='seguimientohc',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
