# Generated by Django 5.2.4 on 2025-11-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0003_alter_detalleshc_options_alter_seguimientohc_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleshc',
            unique_together={('historia_clinica', 'tratamiento', 'pieza_dental', 'cara_dental')},
        ),
    ]
