# Generated by Django 5.2.4 on 2025-11-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0004_alter_detalleshc_unique_together'),
        ('personal', '0006_personal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientohc',
            name='odontologo',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_creados', to='personal.personal'),
            preserve_default=False,
        ),
    ]
