# Generated by Django 5.2.4 on 2025-11-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0005_seguimientohc_odontologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientohc',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
