# Generated by Django 5.2.4 on 2025-11-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0006_alter_seguimientohc_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleshc',
            name='cara_dental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_hc', to='historias_clinicas.carasdentales'),
        ),
        migrations.AlterField(
            model_name='detalleshc',
            name='pieza_dental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_hc', to='historias_clinicas.piezasdentales'),
        ),
    ]
