# Generated by Django 5.2.4 on 2025-09-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_analisis_func_pacientes_analisis_funcional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisisfuncional',
            options={'verbose_name': 'Analisis funcional', 'verbose_name_plural': 'Analisis funcionales'},
        ),
        migrations.AlterModelOptions(
            name='antecedentes',
            options={'verbose_name': 'Antecedente', 'verbose_name_plural': 'Antecedentes'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
