# Generated by Django 5.2.4 on 2025-09-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_analisisfuncional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ge', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='analisis_funcional',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.analisisfuncional'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='antecedentes',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.antecedentes'),
        ),
    ]
