# Generated by Django 5.2.4 on 2025-09-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_generos_alter_pacientes_analisis_funcional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='genero',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='pacientes.generos'),
        ),
    ]
