# Generated by Django 5.2.4 on 2025-09-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_pacientes_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_os', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='OsPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_afiliado', models.CharField(max_length=50)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.obrassociales')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes')),
            ],
            options={
                'verbose_name': 'Obra Social x Paciente',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
    ]
