# Generated by Django 5.2.4 on 2025-09-19 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_obrassociales_ospacientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ospacientes',
            options={'verbose_name': 'Obra Social x Paciente', 'verbose_name_plural': 'Obras Sociales X Pacientes'},
        ),
        migrations.AlterField(
            model_name='ospacientes',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.pacientes'),
        ),
    ]
