# Generated by Django 5.2.4 on 2025-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_ospacientes_options_alter_ospacientes_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
