# Generated by Django 5.2.4 on 2025-10-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_pacientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
