# Generated by Django 5.2.4 on 2025-10-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_pacientes_domicilio_alter_pacientes_email'),
        ('pacientes', '0010_alter_pacientes_domicilio'),
    ]

    operations = [
    ]
