# Generated by Django 5.2.4 on 2025-09-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0006_pacientes_genero'),
        ('personal', '0004_alter_personal_especialidades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_est_tur', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de turnos',
                'verbose_name_plural': 'Estados de Turnos',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField()),
                ('hora_turno', models.TimeField()),
                ('estado_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnos.estadosturnos')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.personal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.pacientes')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
