# Generated by Django 5.2.4 on 2025-10-21 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personal_user'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')], unique=True, verbose_name='Día de la Semana')),
            ],
            options={
                'verbose_name': 'Día de la Semana',
                'verbose_name_plural': 'Días de la Semana',
            },
        ),
        migrations.CreateModel(
            name='HorarioFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True, verbose_name='Hora del Turno')),
            ],
            options={
                'verbose_name': 'Horario Fijo',
                'verbose_name_plural': 'Horarios Fijos',
                'ordering': ['hora'],
            },
        ),
        migrations.AddField(
            model_name='turnos',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del Turno'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='fecha_turno',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='horario_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turnos.horariofijo', verbose_name='Hora'),
        ),
        migrations.AlterUniqueTogether(
            name='turnos',
            unique_together={('odontologo', 'fecha_turno', 'horario_turno')},
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='hora_turno',
        ),
    ]
