# Generated by Django 5.2.4 on 2025-11-15 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personal_user'),
        ('turnos', '0002_diasemana_horariofijo_turnos_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACION', 'Turno Agendado'), ('MODIFICACION', 'Turno Modificado'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ELIMINACION', 'Turno Eliminado (Horario Liberado)')], max_length=20)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('turno_numero', models.IntegerField(blank=True, null=True)),
                ('paciente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('odontologo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_turno', models.DateField(blank=True, null=True)),
                ('horario_turno', models.TimeField(blank=True, null=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_registros', to='turnos.turnos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria_turnos', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Auditoría de Turno',
                'verbose_name_plural': 'Auditorías de Turnos',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['fecha_accion'], name='turnos_audi_fecha_a_8cf76e_idx'), models.Index(fields=['turno'], name='turnos_audi_turno_i_cff0fa_idx'), models.Index(fields=['turno_numero'], name='turnos_audi_turno_n_737001_idx')],
            },
        ),
    ]
