# Generated by Django 5.2.4 on 2025-11-16 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personal_user'),
        ('turnos', '0003_auditoriaturnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_modificados', to='personal.personal', verbose_name='Modificado por'),
        ),
    ]
