# Generated by Django 5.2.4 on 2025-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_especialidades_options_alter_puestos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='personal', to='personal.especialidades'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='matricula',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
