# Generated by Django 5.2.4 on 2025-09-24 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_personal_especialidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='puestos',
        ),
        migrations.AddField(
            model_name='personal',
            name='puesto',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='personal.puestos'),
        ),
    ]
