# Generated by Django 5.2.4 on 2025-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
