# Generated by Django 5.2.4 on 2025-11-17 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_personal_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 11, 17, 22, 38, 28, 47525, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
